# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 438d374608b032cd99d3ba03b10a0fb3d148b719fb58023c4c76d0f778cc1bacd5d9fcf620946691e482e4a071e00215d407cdd8387b099c5ed6deefceb2d064

test:
  secret_key_base: e79826652f4de856305d356dbb7987e5bb0fff635777baa112cb569374212a12a4a7f124f292d2ae42482987a70bda0bbc9104900cc88252d9673c96fa1cf712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
